<?php

/**
 * @file
 * General customizations to compost website.
 */

/*
 * Implements hook_menu()
 */
function compost_customizations_menu() {

  $items = array();

  // Define an always accessible path to receive IPNs.
  $items['paypal/ipn'] = array(
    'page callback' => '_compost_customizations_paypal_process_ipn',
    'page arguments' => array(),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;

}
/*
 * Implements hook_mail()
 */
function compost_customizations_mail_alter(&$message) {
  // Set the from address to the site's email so emails don't get blocked coming from uncontrolled sources
  $site_from_email = variable_get('site_mail',  $message['from']);
  $message['headers']['Return-Path']=  $message['from'];
  $message['headers']['From'] = $message['headers']['Sender']  = $message['from'] = $site_from_email;
}


/*
 * Implements hook_form_FORM_ID_alter()
 */
function compost_customizations_form_user_register_form_alter(&$form, $form_state, $form_id) {

  // Only reveal mobile carrier inquiry if user wants text reminders
  $form['field_mobile_carrier_provider']['#states'] = array(
    'invisible' => array(
      ':input[name="field_reminders[und][2]"]' => array('checked' => FALSE),
    ),
  );

  $form['field_location'][LANGUAGE_NONE][0]['#title'] = t('Address');
  // Defaults set in UI @ admin/config/people/accounts/fields/field_location
  // $form['field_location'][LANGUAGE_NONE][0]['#default_value']['city'] = t('Durham');
  // $form['field_location'][LANGUAGE_NONE][0]['#default_value']['province'] = t('North Carolina');

  // Make non-admin registration subscription level required
  $form['field_subscription_level'][LANGUAGE_NONE]['#required'] = user_access('Administer users') ? FALSE : 1;

  // Add validation to ensure if user wants text messages, that they've selected a mobile carrier
  $form['#validate'][] = '_compost_customizations_mobile_carrier_validate';
}

/*
 * Implements hook_form_FORM_ID_alter()
 */
function compost_customizations_form_user_profile_form_alter(&$form, $form_state, $form_id) {

  // Only reveal mobile carrier inquiry if user wants text reminders
  $form['field_mobile_carrier_provider']['#states'] = array(
    'invisible' => array(
      ':input[name="field_reminders[und][2]"]' => array('checked' => FALSE),
    ),
  );

  // Add validation to handle skip_day
  $form['#validate'][] = '_compost_customizations_user_skip_day_validate';

  $form['field_skip_day'][LANGUAGE_NONE]['#title'] = t('Enter dates you won\'t need a pick up (e.g. on vacation)');

  // Make non-admin subscription level required when updating profile
  $form['field_subscription_level'][LANGUAGE_NONE]['#required'] = user_access('Administer users') ? FALSE : 1;

  // Hide but don't delete previous skip days
  $form = _compost_customizations_hide_past_skip_days($form);

  // Add custom submit handling
  $form['#submit'][] = '_compost_customizations_user_account_submit';
}

/*
 * Validation function for registrants selecting mobile text reminders
 */
function _compost_customizations_mobile_carrier_validate($form, $form_state) {
  $v = $form_state['values'];

  // If user opted in to text reminders, but did not provide mobile provider, set error
  if ($v['field_reminders'][LANGUAGE_NONE][1]['value'] == 2
    && $v['field_mobile_carrier_provider'][LANGUAGE_NONE][0]['value'] == null) {
    form_error($form['field_mobile_carrier_provider'], t('Please select a mobile carrier when opting into text reminders'));
  }
}

/*
 * Validation function for users selecting skip days
 */
function _compost_customizations_user_skip_day_validate($form, $form_state) {

  $today = date('Y-m-d', time());

  // Don't proceed if the user isn't associated to a route to avoid php warnings    
  if (!isset($form_state['user'])) {
      return;
  }

  $route = node_load($form_state['user']->field_route[LANGUAGE_NONE][0]['target_id']);
  $pickup_day = $route->field_pickup_day[LANGUAGE_NONE][0]['value'];

  foreach ($form_state['values']['field_skip_day'][LANGUAGE_NONE] as $key => $date) {

    if (is_numeric($key) && $form_state['user']->field_skip_day[LANGUAGE_NONE][$key]['value'] != $date['value']) {

      // Don't allow NEW submission of any day before today
      if ($date['value'] < $today) {
        form_error($form['field_skip_day'][LANGUAGE_NONE][$key], t('You cannot add skip days from the past.'));
      }
      // Don't allow submission of a different day of the week than the user's scheduled day
      elseif (date('l', strtotime($date['value'])) != $pickup_day) {
          form_error($form['field_skip_day'][LANGUAGE_NONE][$key], t('Please only select one of your future pick up days.
         Your pick ups are on @pickup_day' . '.', array('@pickup_day' => $pickup_day)));
      }
    }
  }
}

/*
 * Implements hook_menu_alter()
 */
function compost_customizations_menu_alter(&$items) {
  // Replace /user/register with /subscribe
  $user_reg = $items['user/register'];
  $items['subscribe'] = $user_reg;
  unset($items['user/register']);
}

/*
 * Listener function to process Paypal IPNs
 *
 * Local testing can be done by mimicking an external POST via curl.  First enable debugger, which sets the debugger
 * cookie.  Then issue:
 * curl [LOCAL-URL]/paypal/ipn -b "ZendDebuggerCookie=127.0.1.1%2C127.0.0.1%3A10137%3A0||004|77742D65|19201" -d "good=golly"
 * -d key value pair can be replaced with a file
 */
function _compost_customizations_paypal_process_ipn() {
  //require_once drupal_get_path('module', 'compost_customizations') . '/IPN_PHP/IPN_PHP.php';

  // Log it
  watchdog('paypal_ipn', 'Post: @Post', array('@Post' => print_r($_POST, TRUE)), WATCHDOG_INFO);

  // @todo: Handle it.  Update when we get live data to test with

  // If IPN for instant payment, set user's selection in his/her profile
  // Set the user's payment selection
}

/**
 * @param $form
 *   Form variable as it passes through hook_form_alter()
 */
function _compost_customizations_hide_past_skip_days($form) {
  $today = date('Y-m-d', time());
  $children = element_children($form['field_skip_day'][LANGUAGE_NONE]);

  foreach ($children as $key) {
    $value = $form['field_skip_day'][LANGUAGE_NONE][$key]['#default_value']['value'];
    if (is_numeric($key) && !empty($value) && $value < $today) {
      $form['field_skip_day'][LANGUAGE_NONE][$key]['#type'] = 'hidden';
    }
  }

  return $form;
}

/**
 * @param $user
 *  A user object
 * @return string
 *  The formatted first and last name of the user
 */
function compost_customizations_format_name($user) {
  $account = user_load($user->uid);

  $first_name = $account->field_first_name[LANGUAGE_NONE][0]['safe_value'];
  $last_name = $account->field_last_name[LANGUAGE_NONE][0]['safe_value'];

  return (!empty($first_name) && !empty($last_name)) ? $first_name . ' ' . $last_name : $account->mail;
}

/**
 * @param $user
 *  User object
 *
 * returns
 *  Email that will go to user's cell phone
 */
function compost_customizations_retrieve_text_email($user) {
  $carrier = $user->field_mobile_carrier_provider[LANGUAGE_NONE][0]['value'];
  $unformatted_phone_number = $user->field_phone_number[LANGUAGE_NONE][0]['value'];
  $formatted_phone_number = preg_replace("/[^0-9]+/", "", $unformatted_phone_number);

  switch ($carrier) {
    case 'Verizon':
      return $formatted_phone_number . '@vtext.com';
    case 'AT&T':
      return $formatted_phone_number . '@txt.att.net';
    case 'Sprint':
      return $formatted_phone_number . '@messaging.sprintpcs.com';
    case 'T-Mobile':
      return $formatted_phone_number . '@tmomail.net';
    case 'U.S. Cellular':
      return $formatted_phone_number . '@email.uscc.net';
    default:
      return false;
  }
}

/*
 * Returns users (objects) that opted into text reminders
 */
function compost_customizations_get_text_reminders() {

  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'user')
    ->fieldCondition('field_active', 'value', 1)
    ->fieldCondition('field_reminders', 'value', 2);

  $result = $query->execute();

  if (isset($result['user'])) {
    $user_uids = array_keys($result['user']);
    $users = entity_load('user', $user_uids);
  }

  $users = _compost_customizations_remove_skippers($users);

  return $users;

}

/*
 * Returns users (objects) that opted into email reminders
 */
function compost_customizations_get_email_reminders() {

  $query = new EntityFieldQuery();

  $query->entityCondition('entity_type', 'user')
    ->fieldCondition('field_reminders', 'value', 1)
    ->fieldCondition('field_active', 'value', 1);

  $result = $query->execute();

  if (isset($result['user'])) {
    $user_uids = array_keys($result['user']);
    $users = entity_load('user', $user_uids);
  }

  $users = _compost_customizations_remove_skippers($users);

  return $users;
}

/*
 * Implements hook_mail()
 */
function compost_customizations_mail($key, &$message, $headers) {

  switch ($key) {
    case 'text_email_reminder':
      $message['body'][] = t('Put your compost bucket(s) out tonight please!  Text back @cell_phone with any issues',
        array('@cell_phone' => $message['params']['captain']->field_phone_number[LANGUAGE_NONE][0]['value']));
      $message['subject'] = t('Compost Bucket Reminder');
      break;
    case 'email_reminder':
      $account = $message['params']['user'];
      $captain = $message['params']['captain'];

      $message['body'][] = t('Dearest @name, Put your compost bucket(s) out tonight please!',
        array('@name' => compost_customizations_format_name($account)));

      $message['body'][] = t('If you do not need service this week, please login to your profile: @profile_link and
      elect for a skip day.', array('@profile_link' => url('user/' . $account->uid . '/edit', array('absolute' => TRUE))));

      $message['body'][] = t('If you need to recover your password to login, you may do so here: !link',
          array('!link' => url('user/password', array('absolute' => TRUE)))) . ',';

      $message['body'][] = t('Please update any of your profile information if it is not correct below');
      $message['body'][] = t('Address: @address',
        array('@address' => $account->field_location[LANGUAGE_NONE][0]['street']));

      if (!empty($account->field_bucket_location)) {
        $message['body'][] = t('Bucket Location: @location',
          array('@location' => $account->field_bucket_location[LANGUAGE_NONE][0]['value']));
      }

      $message['body'][] = t('Phone Number: @phone_number',
        array('@phone_number' => $account->field_phone_number[LANGUAGE_NONE][0]['value']));

      $message['body'][] = t('If you missed pick up or are a drop-off subscriber, the drop-off address is: @addy',
        array('@addy' => $captain->field_location[LANGUAGE_NONE][0]['street']));

      $message['body'][] = t('Thank you so much for your service') . ',';
      $message['body'][] = "- " . t('Your friends @') . ' ' . url('', array('absolute' => TRUE));
      $message['subject'] = t('Reminder: Put out your compost bucket(s)');
  }
}

/*
 * Implements hook_cron()
 */
function compost_customizations_cron() {
  // Timing should be controlled by elysia_cron
  // Fill out queues now, and they get executed as queues later in the cron run

  $text_queue = DrupalQueue::get('text_reminders');
  foreach (compost_customizations_get_text_reminders() as $item) {
    $text_queue->createItem($item);
  }

  $email_queue = DrupalQueue::get('email_reminders');
  foreach (compost_customizations_get_email_reminders() as $item) {
    $email_queue->createItem($item);
  }
}

// Implementation per http://rbayliss.net/drupal-queue-api
/**
 * Implements hook_cron_queue_info()
 */
function compost_customizations_cron_queue_info() {
  $queues['email_reminders'] = array(
    'worker callback' => 'compost_customizations_send_email_reminders',
    'time' => 300,
  );

  $queues['text_reminders'] = array(
    'worker callback' => 'compost_customizations_send_text_reminders',
    'time' => 300,
  );

  return $queues;
}

/**
 * @param $user
 *  User object as queue item
 */
function compost_customizations_send_email_reminders($user) {

  $route = node_load($user->field_route[LANGUAGE_NONE][0]['target_id']);
  $captain = user_load($route->field_route_captain[LANGUAGE_NONE][0]['target_id']);
  $params = array('user' => $user, 'captain' => $captain);
  drupal_mail('compost_customizations', 'email_reminder', $user->mail, $user->language, $params);
}

/**
 * @param $user
 *  User object as queue item
 */
function compost_customizations_send_text_reminders($user) {
  // Grab formatted text email address as well as captains text-back number for message body
  $text_email = compost_customizations_retrieve_text_email($user);
  $route = node_load($user->field_route[LANGUAGE_NONE][0]['target_id']);
  $captain = user_load($route->field_route_captain[LANGUAGE_NONE][0]['target_id']);
  $params = array('captain' => $captain);
  drupal_mail('compost_customizations', 'text_email_reminder', $text_email, $user->language, $params);
}


/**
 * Implements hook_field_formatter_info().
 */
function compost_customizations_field_formatter_info() {
  // Add formatter to show just the street name instead of full location with GPS coordinates
  return array(
    'just_street_name' => array(
      'label' => t('Street name only'),
      'field types' => array('location'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function compost_customizations_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  // Probably should be some qualifier here
  $element[0]['#markup'] = $items[0]['street'];
  return $element;
}

/**
 * @param $users
 *  An array of users keyed by uid
 *
 * Returns all users who haven't skipped the upcoming pick up
 */
function _compost_customizations_remove_skippers($users) {

  $time = time();
  foreach ($users as $user) {
    foreach($user->field_skip_day as $day) {
      $stamp = strtotime($day[0]['value']);
      if ($stamp > $time && $stamp < $time + 7 * 24 * 60 * 60) {
        unset ($users[$user->uid]);
      }
    }
  }

  return $users;

}

/*
 * Implements hook_form_FORM_ID_alter()
 */
function compost_customizations_form_views_exposed_form_alter(&$form, $form_state, $form_id) {
  // Inject our routes as a select option instead of leaving it to text input
  $name = $form_state['view']->name;
  if (isset($form_state['view']) && ($name == 'map' || $name == 'addresses' || $name == 'schedule')){

    $results = db_select('node','n')
      ->fields('n',array('title'))
      ->condition('type','route')
      ->condition('status', 1)
      ->execute()
      ->fetchAllKeyed(0, 0);

    $default['All'] = t('All routes');

    $options = array_merge($default, $results);

    $form['title'] = array(
      '#type' => 'select',
      '#options' => $options,
      '#default_value' => 'All',
    );
  }
}


/**
 * Implements hook_views_pre_render().
 * @param type $view
 */
function compost_customizations_views_pre_render(&$view) {
  if ($view->editing == TRUE) {
    return;
  }

  switch ($view->name) {
    case 'addresses':
      // Use eight days to be safe
      $eight_days_ago = 60 * 60 * 24 * 8;
      $now = time();
      $date_format = 'Y-m-d';
      $today = date($date_format, $now);

      foreach ($view->result as $id => $subscriber) {
        // If skip day is today, show "skip"
        if (!empty($subscriber->field_field_skip_day)) {
          foreach ($subscriber->field_field_skip_day as $skip_day) {
            if (date($date_format, strtotime($skip_day['raw']['value'])) == $today) {
              $view->result[$id]->skip = TRUE;
            }
          }
        }

        // If the user joined in the last 8 days, make sure it's known she's new
        if ($subscriber->users_created > $now - $eight_days_ago) {
          $view->result[$id]->new = TRUE;
        }
      }

    break;
  }

}

/*
 * Implements hook_preprocess_views_view()
 */
function compost_customizations_preprocess_views_view(&$variables, $hook) {

  if ($variables['view']->name != 'addresses') {
    return;
  }

  foreach ($variables['view']->result as $id => $result) {
    if ($result->new == TRUE) {
      $variables['row_classes'][$id][] = t('new');
    }

    if ($result->skip == TRUE) {
      $variables['row_classes'][$id][] = t('skip');
    }
  }
}

/*
 * Implements hook_preprocess_views_data_export_csv_body()
 */
function compost_customizations_preprocess_views_data_export_csv_body(&$variables, $hook) {

  if ($variables['view']->name != 'addresses') {
    return;
  }

  foreach ($variables['view']->result as $id => $result) {
    if ($result->new == TRUE) {
      $variables['themed_rows'][$id]['nothing'] = '"' . t('new') .'"';
    }

    if ($result->skip == TRUE) {
      $variables['themed_rows'][$id]['nothing'] = '"' . t('skip') .'"';
    }
  }
}